### PR TITLE
fix(reactotron-react-native): new arch support

### LINKED ISSUE #1486: [RN new architecture] Invalid non-string URL" for scriptURL - Falling back to localhost
### Describe the bug

I am getting this error in development. `getHost: "Invalid non-string URL" for scriptURL - Falling back to localhost`.

Steps to reproduce. Create RN app. I am in ios with new architecture enabled. This is the reactoronConfig.ts file import Reactotron, {openInEditor, ReactotronReactNative} from 'reactotron-react-native';
import mmkvPlugin from 'reactotron-react-native-mmkv';
import {reactotronRedux} from 'reactotron-redux';
import {storage} from './store';

import config from '../app.json';

Reactotron.configure({
  name: config.name,
})
  .useReactNative({
    networking: {
      ignoreUrls: /symbolicate/,
    },
    editor: false,
    errors: {veto: stackFrame => false},
    overlay: false,
  })
  .use(openInEditor())
  .use(mmkvPlugin<ReactotronReactNative>({storage}))
  .use(reactotronRedux())
  .connect();

export default Reactotron;
 and this is the index.js /**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import 'react-native-gesture-handler';

if (__DEV__) {
	import('@/reactotron.config');
}
AppRegistry.registerComponent(appName, () => App);

### Reactotron version

5.1.7

### PR DESCRIPTION
**Pull request by frankcalise**
## Please verify the following:

- [x] `yarn build-and-test:local` passes
- [ ] I have added tests for any new features, if relevant
- [ ] `README.md` (or relevant documentation) has been updated with your changes

## Describe your PR
- Closes #1486 
- `NativeModules` aren't available in bridgeless, so we utilize the `TurboModuleRegistry` to dig up the same calls we were using (this is backwards compatible)
- [ ] Maybe want to do better TSing over `eslint-disable` but I'll leave that up to @morganick's review 😅 

> [!WARNING]  
> The `DevMenu` change is not Expo Go compatible. This will never work in Expo Go as documented in https://github.com/infinitered/ignite/issues/2678. This would only impact the client devtools code, which they could remove the custom command from the Reactotron configuration (in this repo, it's just in the example app, hence the CNG change)

```bash
ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevMenu' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false.

Modules loaded: {"NativeModules":["PlatformConstants","LogBox","BlobModule","PlatformConstants","SourceCode","PlatformConstants","DeviceInfo"],"TurboModules":[],"NotFound":["DevMenu"]}, js engine: hermes
```

### CODE REVIEW

**Comment by frankcalise** [comment]
@lindboe do you know if this is the proper way to make the TurboModule call? It's all I could find while searching the `facebook/react-native` repo

File: apps/example-app/app/devtools/ReactotronConfig.ts [hunk 1]
```diff
@@ -59,7 +61,7 @@ reactotron.onCustomCommand({
   command: "showDevMenu",
   handler: () => {
     Reactotron.log("Showing React Native dev menu")
-    NativeModules.DevMenu.show()
+    TurboModuleRegistry.getEnforcing<DevMenuSpec>("DevMenu")?.show()
```
Comment (lindboe) [inline apps/example-app/app/devtools/ReactotronConfig.ts:64]: Typically the TM defining library should wrap this `get` call and export it for you. Looks like it should be available from here: https://github.com/facebook/react-native/blob/eb7c43965ed8324aa50e5eab4a6184fd73f217e6/packages/react-native/Libraries/NativeModules/specs/NativeDevMenu.js#L13, which is pointing to https://github.com/facebook/react-native/blob/eb7c43965ed8324aa50e5eab4a6184fd73f217e6/packages/react-native/src/private/specs/modules/NativeDevMenu.js#L13-L23.

Comment (lindboe) [reply apps/example-app/app/devtools/ReactotronConfig.ts:64]: The one thing I'm confused by there is I don't see anything else importing that module? Like I'm not sure how `show` gets called, like when opening the menu, in the current codebase I was searching. May not be in use?

Comment (frankcalise) [reply apps/example-app/app/devtools/ReactotronConfig.ts:64]: https://github.com/facebook/react-native/blob/eb7c43965ed8324aa50e5eab4a6184fd73f217e6/packages/react-native/src/private/specs/modules/NativeDevMenu.js

Comment (frankcalise) [reply apps/example-app/app/devtools/ReactotronConfig.ts:64]: Yeah something seems off, the calls work though 🤷

Comment (lindboe) [reply apps/example-app/app/devtools/ReactotronConfig.ts:64]: @frankcalise The import you used is the second link I included, but I think the first link is where you're meant to import it from, because the second one says `private` in the path.

File: lib/reactotron-react-native/src/reactotron-react-native.ts [hunk 2]
```diff
@@ -86,8 +79,8 @@ const DEFAULTS: ClientOptions<ReactotronReactNative> = {
       name,
       Platform.OS,
       Platform.Version,
-      constants.systemName,
-      constants.Model,
+      getReactNativePlatformConstants().systemName,
+      getReactNativePlatformConstants().Model,
```
[the remark this answers is not in the document]
Comment (frankcalise) [reply lib/reactotron-react-native/src/reactotron-react-native.ts:83]: I mean it's only really doing anything once since it's platform specific but will do

**Comment by frankcalise** [comment]
@morganick turns out the DevMenu module looks botched on Android only actually. may have to take another route here, but maybe comment out that custom command to further test the scriptURL part at least

File: lib/reactotron-react-native/src/helpers/getReactNativePlatformConstants.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
+import { Platform, PlatformIOSStatic, PlatformAndroidStatic } from "react-native"
+
+export default function getReactNativePlatformConstants(): any {
```
[the remark this answers is not in the document]
Comment (frankcalise) [reply lib/reactotron-react-native/src/helpers/getReactNativePlatformConstants.ts]: updated

File: apps/example-app/app/devtools/ReactotronConfig.ts (hunk 1 above)
Comment (frankcalise) [reply apps/example-app/app/devtools/ReactotronConfig.ts]: An issue has been opened related to this: https://github.com/facebook/react-native/issues/46679

**Comment by frankcalise** [comment]
@morganick I'm pretty sure that still worked for me, I will have to double check. Was it broken on old arch or new or both?

**Comment by lindboe** [comment]
@morganick Frank and I tested out shake on Android device/sim and it appeared to work for us, any more reproduction steps to try?

**Review by lindboe — APPROVED** [review]
Reviewed together, LGTM!

**Review by morganick — APPROVED** [review]
No longer able to reproduce issue with shake to activate dev menu through reactotron.

**Comment by morganick** [comment]
Thanks for fixing this @frankcalise

**Comment by awadeyar1** [comment]
This issue still happening with RN 0.75.4 with old architecture.

**Comment by johhansantana** [comment]
getting the `Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Invariant Violation: TurboModuleRegistry.getEnforcing` error only on `Release` mode on iOS.

Downgrading to reactotron-react-native 5.0.0 seems to work though

**Comment by johhansantana** [comment]
@frankcalise I've tried replicating it multiple times in different react-native and expo versions but can't really get it to give me the error. Maybe it's something specific with my Podfile. I'll try and play around with it and see if I can get it running correctly. Any tips on what should I look for? I'm currently on react-native version `0.72.10`
