### PR TITLE
Move commandListener callbacks outside of render cycle

### LINKED ISSUE #1542: reactotron-core-ui: Image Overlay is broken with `Warning: Cannot update a component (`t`) while rendering a different component (`Provider`)`
### Describe the bug

When applying an image overlay, I'm getting this error:

```
Warning: Cannot update a component (`t`) while rendering a different component (`Provider`). To locate the bad setState() call inside `Provider`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at Provider (webpack-internal:///./src/renderer/contexts/Standalone/index.tsx:25:3)
    at Provider (webpack-internal:///./src/renderer/contexts/Layout/index.tsx:16:3)
    at RootContextProvider (webpack-internal:///./src/renderer/contexts/index.tsx:10:3)
    at Router (webpack-internal:///../../node_modules/react-router/dist/index.js:1193:15)
    at HashRouter (webpack-internal:///../../node_modules/react-router-dom/dist/index.js:766:5)
    at App
    at div
    at O (webpack-internal:///../../node_modules/styled-components/dist/styled-components.browser.esm.js:27:23707)
    at tt (webpack-internal:///../../node_modules/styled-components/dist/styled-components.browser.esm.js:27:20427)
    at ReactotronAppProvider (webpack-internal:///../../lib/reactotron-core-ui/dist/index.esm.js:603:15)
```

I'm running with a local Reactotron dev build but also seems broken in prod.

### Reactotron version

reactotron-core-ui@2.4.0

### PR DESCRIPTION
**Pull request by jamonholmgren**
The commandListener callbacks were running during the `dispatch`, which breaks React since it's during a render cycle.

This moves it outside of the `dispatch` call.

Fixes #1542.

- [x] `yarn build-and-test:local` passes

Also I'm going to kill this Redux-ish state management system and move to something closer to MobX or Legend State. It's awful to work with.

### CODE REVIEW

File: apps/reactotron-app/src/renderer/contexts/Standalone/useStandalone.ts [hunk 1]
```diff
@@ -135,12 +135,15 @@ export function reducer(state: State, action: Action) {
           return
         }
 
-        draftState.commandListeners.forEach((cl) => cl(action.payload))
```
Comment (jamonholmgren) [inline apps/reactotron-app/src/renderer/contexts/Standalone/useStandalone.ts:138]: This is now on line 217 below.

**Review by frankcalise — APPROVED** [review]
Great stuff, this has been borked for a while I think!

**Comment by jamonholmgren** [comment]
@joshuayoes How do I release using the new system?

**Comment by frankcalise** [comment]
@jamonholmgren we built this cool thing called IR docs 

https://docs.infinite.red/reactotron/contributing/releasing/

**Comment by jamonholmgren** [comment]
@frankcalise I actually read that, believe it or not ... but I don't know if there's a format for the commit messages to get picked up by the release notes / changelog.

**Comment by frankcalise** [comment]
fair, judging by the merged PRs it looks to be the same as Ignite

**Comment by joshuayoes** [comment]
@jamonholmgren you make a change in the workspace you want to release and the use semantic version keywords in your squash commit title: feat, fix, or chore
